#!/bin/bash

echo    "##################################################"
echo    "#######                                    #######"
echo    "#######    generating i3 config ...        #######"
echo -n "#######    "
echo -n .

IFS=$'\n'
echo -n .

x_server=$(echo ${DISPLAY} | cut -d: -f1 )
x_screen=$(echo ${DISPLAY} | cut -d: -f2 )
[[ -z "${x_server}" ]] && display="${hostnamE}:${x_screen}" || display="${DISPLAY}" 
echo -n .

d="${HOME}/.config/i3"
echo -n .

file_base="config_${display}"
[[ -e "${d}/${file_base}.parts" ]] || file_base="config_default"
echo -n .

parts_file="${d}/${file_base}.parts"
lf="${d}/${file_base}.autogenerated.loaded"
f="${d}/${file_base}.autogenerated"
echo -n .

[[ -e "${lf}" ]] && MD5SUM=$(md5sum "${lf}")
echo -n .

# empty the file
echo "" > "${f}"
echo -n .

for line in $(cat "${parts_file}") ; do
    msg="###   gent from ${d}/${line}   ###"
    printf "%.${#msg}s\n" "#########################################################################################################################"  >> "${f}"
    echo  "${msg}" >> "${f}"
    printf "%.${#msg}s\n" "#########################################################################################################################"  >> "${f}"
    cat "${d}/${line}" >> "${f}"
    echo >> "${f}"
done
echo -n .

[[ -v MD5SUM ]] && [[ "${MD5SUM}" = $(md5sum "${f}") ]] \
    && echo                     "                       #######" \
    && echo "#######    md5sum match, skipping reload   #######" \
    && echo "#######                                    #######" \
    && echo "##################################################" \
    && exit

echo                     "                       #######"
echo "#######    reloading i3 config ...         #######"
i3-msg -t command reload && [[ ! -e "$lf" ]] && ln -s "${f}" "${lf}"
echo "#######     done                           #######"
echo "#######     exit code was: $?              #######"
echo "##################################################"
